version: "3"
volumes:
    violetDb:

networks:
    violetNet:
        driver: bridge

services:
    db:
        image: mariadb:10.3
        env_file: './database.env'
        networks:
            - violetNet
        volumes:
            - 'violetDb:/var/lib/mysql'
        container_name: violet-mysql
        environment:
            MARIADB_DATABASE: violet

    main:
        build:
            context: .
            dockerfile: Dockerfile
        image: violet
        networks:
            - violetNet
        container_name: violet-main
        env_file: main.env
        depends_on:
            - db
        ports:
            - 127.0.0.1:3000:3000
